---
title: "Global Poverty Trends (2016-2026)"
format: html
embed-resources: true
editor: visual
execute:
  warning: false
  message: false
---

Data Sources: Our World in Data - Poverty ([World Bank (2026). Poverty and Inequality Platform (version 20260324_2021 and 20260324_2017) \[Data set\]. World Bank Group. https://pip.worldbank.org/.](https://pip.worldbank.org/)) ; World Bank Global Economic Indicators (2010-2025)(<https://www.kaggle.com/datasets/tanishksharma9905/global-economic-indicators-20102025?resource=download>)

# Visualization 1

```{r}
library(tidyverse)
library(readr)
owi_poverty <- read_csv("data/share-of-population-living-in-extreme-poverty.csv") 

poverty_world <- owi_poverty |>
  filter(Country == c("World", "World (excluding China)", "World (excluding India)"))
  
ggplot(data = poverty_world,
       mapping = aes(x = Year,
                     y = `Share below $3 a day`,
                     color = Country)) +
  geom_point(size = 2, shape = 16) +
  geom_text(aes(label = round(`Share below $3 a day`, 1)),
            vjust = -0.7,
            size = 3) +
  geom_smooth(method = "loess",
              se = FALSE) +
  scale_x_continuous(breaks = seq(2016, 2026, by = 1)) +
  scale_y_continuous(breaks = seq(9.5, 15.5, by = 1)) +
  theme_minimal() +
  labs(title = paste("Share of global population below 3$ per day",
                     "\n3 different measures, 2016-2026"),
       subtitle = paste("China and India have proven to significantly ",
                        "influenced\nglobal poverty levels over the last",
                        "decade"),
       caption = "Source: World Bank Our World in Data Poverty Database")
  
  
  
```

# Visualization 2

```{r}
library(tidyverse)
library(dplyr)

WB_econ_indicators <- read_csv("data/world_bank_data_2025.csv") 

#subset of countries: bottom 10 GDP per capita
bottom5_gdppc <- WB_econ_indicators |>
  group_by(year) |>
  slice_min(`GDP per Capita (Current USD)`, n = 5)

bottom5_gdppc_2023 <- bottom5_gdppc |>
  filter(year == 2023) |>
  mutate(
    region = case_when(
      country_name %in% c("Afghanistan", "Yemen, Rep.") ~ "Middle East",
      country_name == "Central African Republic" ~ "Central Africa",
      country_name %in% c("Burundi", "Madagascar") ~ "East Africa"
    ))

ggplot(data = bottom5_gdppc_2023,
       mapping = aes(x = country_name,
                     y = `GDP per Capita (Current USD)`,
                     fill = region)) +
  geom_col() +
  scale_x_discrete(guide = guide_axis(angle = 30)) +
  labs(x = "Country",
       title = "Bottom 5 Countries by GDP per Capita (in current USD), 2023",
       subtitle = paste("All 5 countries with the lowest GDP per capita",
                        "globally are located in Africa\nor the Middle East"),
       caption = "Source: World Bank Global Economic Indicators, 2010-2025") +
  theme_minimal()
  


```

# Visualization 3

```{r}
library(tidyverse)
library(ggrepel)

WB_econ_indicators_2023 <- WB_econ_indicators |>
  filter(year == 2023)

outliers <- WB_econ_indicators_2023 |>
  filter(
    `GDP Growth (% Annual)` < -5 |
    `GDP Growth (% Annual)` > 10 |
    `Unemployment Rate (%)` > 20
  )

ggplot(data = WB_econ_indicators_2023,
       mapping = aes(x = `GDP Growth (% Annual)`,
                     y = `Unemployment Rate (%)`,
                     size = `GDP per Capita (Current USD)`)) +
  geom_point(shape = 21,
             color = "white",
             fill = "red",
             alpha = 0.8) +
  geom_text_repel(data = outliers,
                  aes(label = country_name),
                  size = 2.5) +
  scale_size_area(name = "GDP per Capita (Current USD)",
                  max_size = 20) +
  labs(title = "Global Economic Growth, Unemployment, and Income, 2023",
       subtitle = paste("Outlier countries in either unemployment or GDP",
       "growth\nare labeled, point size represents GDP per capita"),
       caption = "Source: World Bank Global Economic Indicators, 2010-2025") +
  theme_minimal() +
  theme(
    legend.key.size = unit(0.5, "cm"),
    legend.text = element_text(size = 5),
    legend.title = element_text(size = 6)
  ) 

```

# Visualization 4

```{r}
library(tidyverse)

WB_econ_indicators <- read_csv("data/world_bank_data_2025.csv")

bottom5 <- WB_econ_indicators |>
  filter(year == 2019) |>
  slice_min(`GDP per Capita (Current USD)`, n = 5) |>
  pull(country_name)

top5 <- WB_econ_indicators |>
  filter(year == 2019) |>
  slice_max(`GDP per Capita (Current USD)`, n = 5) |>
  pull(country_name)

covid_data <- WB_econ_indicators |>
  filter(
    year >= 2018,
    year <= 2023,
    country_name %in% c(bottom5, top5)
  ) |>
  mutate(
    group = case_when(
      country_name %in% bottom5 ~ "Bottom 5",
      country_name %in% top5 ~ "Top 5"
    )
  )

covid_summary <- covid_data |>
  group_by(year, group) |>
  summarize(
    avg_growth = mean(`GDP Growth (% Annual)`, na.rm = TRUE)
  )

ggplot(data = covid_summary,
       mapping = aes(x = year,
                     y = avg_growth,
                     color = group,
                     linetype = group)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3,
             alpha = 0.8) +
  geom_vline(xintercept = 2020,
             linetype = "dotted") +
  scale_linetype(guide = "none") +
  labs(
    x = "Year",
    y = "Average GDP Growth (% Annual)",
    color = "Country Group",
    title = paste("COVID-19's Economic Impact on the World's Wealthiest",
                  "and\nPoorest 5 Countries by GDP per Capita"),
    subtitle = paste("Policies which allowed the wealthiest 5 countries",
                     "to recover their pre-shock\naverage GDP growth",
                     "significantly more quickly than the poorest 5",
                     "ultimately\ncaused a subsequent drop below",
                     "that of the poorest 5"),
    caption = "Source: World Bank Global Economic Indicators, 2010-2025") +
  theme_classic()
  
```
